#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
A tool for building and making queries to a paikkis sqlite database
on the command line.

Usage:
    paikkis build [options]
    paikkis search [options] (QUERY ...)
    paikkis info <ID>

Arguments:
  QUERY   No need to escape the query, multiple arguments are joined by spaces

Options:
    -h --help                         Show this screen
    -v, --verbose                     Verbose output for debugging [defaut: False]
    -i <input>, --input-file=<input>  FILE to read CSV from [default: PNR_2012_01.TXT]
    -d <db>, --database=<db>          FILE to use as the database [default: paikkis.db]
"""
from __future__ import print_function
import sys
import codecs
import json
from docopt import docopt
from db import build, search, info

o8 = codecs.getwriter('utf-8')(sys.stdout)
e8 = codecs.getwriter('utf-8')(sys.stderr)


if __name__ == '__main__':
    args = docopt(__doc__)
    # print(args)

    if args['build']:
        build(input=args['--input-file'], database=args['--database'],
              verbose=args['--verbose'])
    elif args['search']:
        result = search(database=args['--database'], verbose=args['--verbose'],
                        query=' '.join([q.decode('utf-8') for q in args['QUERY']]))
        print(json.dumps(result, ensure_ascii=False, indent=2), file=o8)
    elif args['info']:
        result = info(database=args['--database'], verbose=args['--verbose'],
                      id=args["<ID>"])
        print(json.dumps(result, ensure_ascii=False, indent=2), file=o8)
